# Generated by Django 5.2.3 on 2025-06-26 17:37

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.get_or_create(name='Owner')
    Role.objects.get_or_create(name='Seeker')



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles, )
    ]
